apiVersion: v1
kind: Service
metadata:
  name: s3-proxy
  labels:
    app.kubernetes.io/name: s3-proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: s3-proxy
