service:
  type: NodePort
  ports:
    - name: http
      port: 31080
      protocol: TCP
      targetPort: 31080
      nodePort: 31080
    - name: envoy-admin
      port: 15000
      protocol: TCP
      targetPort: 15000

resources:
  requests:
    memory: "0"
    cpu: "0"
  limits:
    memory: 1Gi
    cpu: "1"
