## https://github.com/minio/minio/blob/master/helm/minio/values.yaml

mode: standalone

rootUser: minio
rootPassword: minio123

replicas: 1

resources:
  requests:
    memory: "0"
    cpu: "0"
  limits:
    memory: 1Gi
    cpu: "1"

persistence:
  enabled: true
  volumeName: minio
  size: 1Gi

users:
  - accessKey: console
    secretKey: console123
    policy: consoleAdmin
  - accessKey: user
    secretKey: user1234
    policy: readwrite

buckets:
  - name: bucket
    policy: none
    purge: false
    versioning: false
    objectlocking: false

customCommands:
  - command: cp /etc/hostname myminio/bucket/test.txt --attr "Content-Type=text/plain"
